### ISSUE TITLE
Running a selection or identification, then searching, queries the data based on the previous selection.

### ISSUE THREAD

**Issue by chughes-lincoln** [geomoose/gm3#685] opened 2021-08-31 23:37 UTC
For example, if I load the demo and do a single-field search for 'Smith', I'll get 83 results.
If I then select a subset of those results, and then run the same query, I only get results 
that were contained in the previous selection. (If I do an identification of a parcel that is owned
by Smith, a subsequent single-field search for 'Smith' only returns the parcel that I previously identified).

Subsequently, if I clear the results and the previous selection, and then run the single-field
search for 'Smith', I get all 83 results.

I'm not sure what exactly is causing the issue, but it looks like it was introduced in https://github.com/geomoose/gm3/pull/643, specifically, changes that were made to the service manager javascript to get buffer all working.

I rebuilt the minified javascript after adding back in the line of code in `serviceManager.js` that cleared out the previous selection features, which fixed the search issue, though I'm certain that was removed to get the buffer working.

**Comment by chughes-lincoln** [comment] 2021-09-02 21:17
It seems like the the line of code that clears the previous selection was moved to a specific code block for bufferAll, resulting in the previous selection geometry not being cleared when running a search.

I modified the `search.js` dispatchQuery section to use `this.selection` instead of `selection`, which appears to have fixed the search issue while still allowing buffer all, but I'm not sure if that's the desired adjustment that won't cause other issues now or in the future. 

```
Application.dispatchQuery(
            this.name,
            this.selection,
            this.prepareFields(fields),
            this.getSearchLayers(this.searchLayers, fields),
            templates
        );
```

**Comment by klassenjs** [comment] 2022-09-25 21:53
Closing as duplicate of #717, even though #717 is actually a duplicate of this one, #717 has more progress so keeping it instead.

**Closed by klassenjs** 2022-09-25 21:53 UTC
