### ISSUE TITLE
Highlight on Identify doesn't work on vector layer when "Drawing and Markup" layer is on

### ISSUE THREAD

**Issue by brentfraser** [geomoose/gm3#577] opened 2020-07-29 23:41 UTC
In the demo, do an Identify on the "AGS Dakota County Runways" layer with the "Drawing and Markup" layer on.  The feature is not highlighted.

Now turn off the "Drawing and Markup" layer, and do Identify on the "AGS Dakota County Runways" layer.  The Runway is highlighted.

**Comment by chughes-lincoln** [comment] 2020-08-27 23:15
I'm noticing the same issue when I have identify turned off for the "Drawing and Markup" layer, though it will only highlight one of my identifiable layers at a time. Though based on issue https://github.com/geomoose/gm3/issues/576, perhaps the issue is now that it does highlight with the drawing and markup layer off, rather than it does when it's on.

**Comment by brentfraser** [comment] 2020-08-27 23:36
I'm not sure I follow.  Highlight only works with "Drawing and Markup" layer off and only highlights your vector layers.

**Comment by chughes-lincoln** [comment] 2020-08-27 23:59
I meant to say rather than it doesn't highlight when the Drawing and Markup layer is on. The issue is that even when the Drawing and Markup layer is off, it still shouldn't highlight because it's wms (or at least it should be consistent).

**Comment by brentfraser** [comment] 2020-08-28 00:50
I agree.  Only vector layers will highlight (or image layers like WMS if query-as=a WFS layer is set)

**Comment by theduckylittle** [comment] 2021-11-19 04:53
I think the PR will fix this! Good catch everyone!

**Comment by chughes-lincoln** [comment] 2021-11-22 22:07
This now returns consistent results for me (i.e. it always highlights all identifiable layers regardless of whether the drawing and markup layer is on or not). My only thought is that this might warrant the desire to turn off the highlight for identify (i.e. perhaps a highlight: false parameter in the identify app.js similar to turning off the zoom to results). 

For the demo there are only a few identifiable layers, and the most common result is Parcels, so the highlight results are pretty straightforward. For others you could have a dozen identifiable layers, all with very different geometries that are returning highlights on top of each other, which could cause more confusion than value. The ability to configure it could be useful.

**Comment by theduckylittle** [comment] 2021-11-23 03:22
@chughes-lincoln - Go ahead an open a separate ticket on that issue. I'm going to close this one since it fixes the issue as described.

**Closed by theduckylittle** 2021-11-23 03:22 UTC
Labels: bug
