### ISSUE TITLE
Identify not working on Mobile

### ISSUE THREAD

**Issue by goo160047co** [geomoose/gm3#399] opened 2019-06-04 20:48 UTC
It looks like when you try to identify a parcel on the mobile(Lite) example. When you try to click the identify button on the fourth tab over (wrench) on the top it pushes you to the fifth tab(table) and not back to the map. When you click on the map it is blank. I was wondering if anybody has work around to fix this issue?

**Comment by theduckylittle** [comment] 2019-06-05 04:20
I'll need to take a look at this. We hadn't originally had a lot of interest in the mobile version so it hasn't received quite as much love.

**Comment by tchaddad** [comment] 2019-12-11 20:14
This one is working for me too - I'll let @goo160047co  close...

**Comment by tchaddad** [comment] 2020-01-16 16:31
Confirmed working well by others as well, so closing.

**Comment by tchaddad** [comment] 2020-01-31 19:40
Looks like this broke again between 3.4.1 and 3.5

**Comment by tchaddad** [comment] 2020-01-31 19:43
Confirmed broken on demo

**Comment by theduckylittle** [comment] 2020-02-10 02:31
@tchaddad new day, new fix.

**Closed** 2020-06-02 04:14 UTC
Labels: bug
