### ISSUE TITLE
Select - Identify - Select

### ISSUE THREAD

**Issue by tchaddad** [geomoose/gm3#717] opened 2022-03-18 20:05 UTC
Issue reported from the field - confirmed in demo.

- User does a search on say the parcel layer (e.g. search for "Jim" in the owner field of parcel layer - 2 results)
- User then zooms to a result to inspect, and chooses to use Identify tool to click on surrounding parcels for more info
- User then tries to do another search on the parcels layer (any form of search), but no results return

The expected behaviour is that users clear the previous search results (trash can) before doing a new search, but this is not obvious and no warning is returned when zero results are returned the second time.

maybe a mild alert similar to the prompt for no inputs or the one below would improve the situation?

![image](https://user-images.githubusercontent.com/1042618/159075706-bc1a7838-52ad-465d-a1e6-23f461dbeb3a.png)

Suggest the alert is worded something like "No results returned. Make sure previous selections are properly cleared by clicking below, and try again."

**Comment by chughes-lincoln** [comment] 2022-03-21 20:19
I think this is the same issue as https://github.com/geomoose/gm3/issues/685
In this case if you search Jim (2 results), then do an identify on one of the Jimenez's, then search Jim again,
you only get the result that you identified in your search result.

**Comment by tchaddad** [comment] 2022-03-25 04:17
Well, in this case if you search for 'Jim' the second time, you get zero results, so maybe not exactly the same? 

You can rescue the state by dumping the trash, after which search will work as expected, so that's the reason for suggesting a prompt...

**Comment by chughes-lincoln** [comment] 2022-03-25 15:10
I think the issue is that if you do a select or identification, then a search, you only get results that were in that select or identification (so I _do_ get results for the second 'Jim' search, but only if it was one of the results that I identified). Is the search supposed to query based on previous results? If feel like that's a bit unintuitive to the user (partly because the other tools aren't limited to the current selection set on the map, unless you specifically choose 'Feature from Results').

**Comment by klassenjs** [comment] 2022-09-25 21:46
Validated in 3.11

**Comment by theduckylittle** [comment] 2022-09-25 22:24
Fixed in c4066a2401b2ebd978a3e488ec4c22f1fc319b29

**Closed by theduckylittle** 2022-09-25 22:24 UTC
Labels: enhancement
