### ISSUE TITLE
Not all backgrounds display

### ISSUE THREAD

**Issue by elil** [geomoose/gm3#160] opened 2017-06-23 16:49 UTC
On "OpenStreetMap - Black and White" nothing displays and I get this error in firebug: Loading mixed (insecure) display content "http://a.tiles.wmflabs.org/bw-mapnik/12/985/1479.png" on a secure page

It looks like this might be available in [https](https://a.tiles.wmflabs.org/bw-mapnik/12/985/1479.png) as well but the certificate is not entirely valid. 

On "Reprojected Regional Aerial" nothing displays and I don't see anything in firebug.  Print logs errors in firebug.

USGS DOQs and Topo Quads are annoyingly slow.  They also don't print on the first try.  Returning to them later and trying again succeeds in printing.  Also, sometime when switching between these two, the wrong one displays.  

ArcGIS 9.3 Rest Example does not print.  Firebug logs some errors while printing. 

Bing Roads and Aerials do not display.  Also, does not print.  Print logs errors in firebug.

**Comment by klassenjs** [comment] 2017-06-23 21:36
I know the B&W layer used to work (albeit with a warning).  Is this a regression caused by #148?

**Comment by klassenjs** [comment] 2017-06-23 21:40
The print preview dialog is an interesting work around.  For "reasons" (as Dan would say) it is difficult to detect when all the layers have finished rendering.  By waiting for the user to click print, it is a work around to have the user verify the map is right before generating the PDF.  The print preview feature was a pleasent side effect.

**Comment by klassenjs** [comment] 2017-06-23 21:42
Are all the background layers OK to allow to print (license/terms of use)?  If not we probably need a layer flag for don't allow print and if it is set throw a warning to the user when they start a print.

**Comment by theduckylittle** [comment] 2017-06-24 22:34
Lemme break this down:

1. Regional aerial: just fixed it.  There was a projections support issue. The MS4W demo data package will need updated and I'm not sure if GeoMoose.org is updating the data repo automatically.
2. Everything else is in PR #162.

**Comment by theduckylittle** [comment] 2017-06-24 23:06
PR's are ready, review should happen shortly.

**Comment by elil** [comment] 2017-06-26 15:24
On "OpenStreetMap - Black and White" now displays.  It does not print but I think that is by design.  If that is by design, there should be some message to the effect, "blah layer does not print."

"Reprojected Regional Aerial" now displays and prints.

USGS DOQs and Topo Quads are still a little slow.  When switching between these two, the wrong one still displays sometimes.

ArcGIS 9.3 Rest Example now prints. 

Bing Roads and Aerials have been removed so are no longer relevant.

**Comment by theduckylittle** [comment] 2017-06-26 20:26
@elil PR #171 will add some help for the user to know that there will be difference between the printed image and the PDF.  Knowing which layers are specifically problematic is hard for the print dialog.  Users interact with the *catalog* which uses different label conventions than the *map-source* data which is what the print dialog uses.  I'm hoping that a general disclaimer is enough to satisfy everyone's needs without adding a ton of code complication.

Also, do we really want to keep the USGS layers if they suck so much? I'm open to alternatives.  These just happened to be popular for a stay.

**Comment by elil** [comment] 2017-06-26 21:03
Pertaining to USGS layers, can you use them without a delay significant enough that causes you to conclude that they are broken?  If they are slow enough to cause a "reasonable" user to conclude they are broken, then they need to go.

**Comment by theduckylittle** [comment] 2017-06-26 21:05
S**t, I feel as if they're broken half the time.  And I have firebug/devtools open all the time.

**Comment by elil** [comment] 2017-06-26 21:07
Maybe these should go the way of Bing?  Leave them in the demo but comment them in the Catalog section.

**Comment by theduckylittle** [comment] 2017-06-28 14:26
Removed the USUGS layers using comments and put in a warning.

**Comment by klassenjs** [comment] 2017-06-29 03:10
Yeah sometimes USGS services work great, sometimes they are dead.

**Comment by theduckylittle** [comment] 2017-06-29 03:57
Closing. If we get better stuff we can merge it.

**Closed by theduckylittle** 2017-06-29 03:57 UTC
Labels: bug, review-me
